<a href="https://colab.research.google.com/github/Arpita6379/Credit-Card-Fraud-Detection/blob/main/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# Loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('creditcard.csv')

In [ ]:
# First five raws of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
39697,39927,-1.466679,2.425732,0.877724,3.950765,0.762477,1.162748,0.575625,-0.288354,-1.357990,...,0.186051,0.571010,-0.107517,-0.754306,-0.752828,0.113179,-2.079421,-0.809173,1.50,0.0
39698,39927,-0.523165,-0.100021,0.892966,-1.900405,-0.156870,-0.783894,0.917683,-0.308345,-1.305284,...,-0.082504,-0.414677,-0.063392,-0.087455,-0.303383,-0.682889,-0.178417,-0.137169,100.92,0.0
39699,39928,-2.768425,-1.007072,2.151127,0.117797,1.283178,1.869731,-0.562240,0.820374,0.348797,...,-0.182963,0.778210,0.904077,-1.288631,0.212441,0.483975,-0.027614,-0.582813,11.99,0.0
39700,39928,1.201327,0.158614,-0.325263,0.471667,0.086446,-0.770357,0.422151,-0.205277,-0.451865,...,0.027664,-0.018485,-0.199382,0.053605,0.683829,0.428416,-0.077342,-0.006394,45.00,0.0
39701,39929,1.097669,-1.315782,0.659681,-0.683915,-1.342612,0.332629,-1.110900,0.194811,-0.248825,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39702 entries, 0 to 39701
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    39702 non-null  int64
 1   V1      39702 non-null  float64
 2   V2      39702 non-null  float64
 3   V3      39702 non-null  float64
 4   V4      39702 non-null  float64
 5   V5      39702 non-null  float64
 6   V6      39702 non-null  float64
 7   V7      39702 non-null  float64
 8   V8      39702 non-null  float64
 9   V9      39702 non-null  float64
 10  V10     39702 non-null  float64
 11  V11     39702 non-null  float64
 12  V12     39702 non-null  float64
 13  V13     39701 non-null  float64
 14  V14     39701 non-null  float64
 15  V15     39701 non-null  float64
 16  V16     39701 non-null  float64
 17  V17     39701 non-null  float64
 18  V18     39701 non-null  float64
 19  V19     39701 non-null  float64
 20  V20     39701 non-null  float64
 21  V21     39701 non-null  float64
 22  V22     39701 non-null  float64
 23  V23     39701 non-null  float64
 24  V24     39701 non-null  float64
 25  V25     39701 non-null  float64
 26  V26     39701 non-null  float64
 27  V27     39701 non-null  float64
 28  V28     39701 non-null  float64
 29  Amount  39701 non-null  float64
 30  Class   39701 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 9.4 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
credit_card_data.shape

(39702, 31)

In [ ]:
credit_card_data['Amount'].fillna(credit_card_data['Amount'].mean(), inplace=True)

<ipython-input-10-b6c14c9c1def>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['Amount'].fillna(credit_card_data['Amount'].mean(), inplace=True)

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    0
Class     1
dtype: int64

In [ ]:
credit_card_data['V20'].fillna(credit_card_data['V20'].mean(), inplace=True)
credit_card_data['V21'].fillna(credit_card_data['V21'].mean(), inplace=True)
credit_card_data['V22'].fillna(credit_card_data['V22'].mean(), inplace=True)
credit_card_data['V23'].fillna(credit_card_data['V23'].mean(), inplace=True)
credit_card_data['V24'].fillna(credit_card_data['V24'].mean(), inplace=True)
credit_card_data['V25'].fillna(credit_card_data['V25'].mean(), inplace=True)
credit_card_data['V26'].fillna(credit_card_data['V26'].mean(), inplace=True)
credit_card_data['V27'].fillna(credit_card_data['V27'].mean(), inplace=True)
credit_card_data['V28'].fillna(credit_card_data['V28'].mean(), inplace=True)
credit_card_data['V11'].fillna(credit_card_data['V11'].mean(), inplace=True)
credit_card_data['V12'].fillna(credit_card_data['V12'].mean(), inplace=True)
credit_card_data['V13'].fillna(credit_card_data['V13'].mean(), inplace=True)
credit_card_data['V14'].fillna(credit_card_data['V14'].mean(), inplace=True)
credit_card_data['V15'].fillna(credit_card_data['V15'].mean(), inplace=True)
credit_card_data['V16'].fillna(credit_card_data['V16'].mean(), inplace=True)
credit_card_data['V17'].fillna(credit_card_data['V17'].mean(), inplace=True)
credit_card_data['V18'].fillna(credit_card_data['V18'].mean(), inplace=True)

<ipython-input-12-c4a427ee5b59>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V20'].fillna(credit_card_data['V20'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V21'].fillna(credit_card_data['V21'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V22'].fillna(credit_card_data['V22'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V23'].fillna(credit_card_data['V23'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V24'].fillna(credit_card_data['V24'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V26'].fillna(credit_card_data['V26'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V27'].fillna(credit_card_data['V27'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V28'].fillna(credit_card_data['V28'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V11'].fillna(credit_card_data['V11'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V12'].fillna(credit_card_data['V12'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V13'].fillna(credit_card_data['V13'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V14'].fillna(credit_card_data['V14'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V15'].fillna(credit_card_data['V15'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V16'].fillna(credit_card_data['V16'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V17'].fillna(credit_card_data['V17'].mean(), inplace=True)
<ipython-input-12-c4a427ee5b59>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V18'].fillna(credit_card_data['V18'].mean(), inplace=True)

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       1
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     1
dtype: int64

In [ ]:
credit_card_data['V19'].fillna(credit_card_data['V19'].mean(), inplace=True)
credit_card_data['Class'].fillna(credit_card_data['Class'].mean(), inplace=True)

<ipython-input-14-c497bec2d80c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['V19'].fillna(credit_card_data['V19'].mean(), inplace=True)
<ipython-input-14-c497bec2d80c>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_card_data['Class'].fillna(credit_card_data['Class'].mean(), inplace=True)

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.00000    39597
1.00000      104
0.00262        1
Name: count, dtype: int64

This Dataset is highly unbalanced

0 --> Normal Transaction
1 --> fraudulent Transaction

In [ ]:
# seprating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(39597, 31)
(104, 31)

In [ ]:
# statistical meausers of data
legit.Amount.describe()

count    39597.000000
mean        87.420700
std        234.514383
min          0.000000
25%          7.420000
50%         23.500000
75%         79.000000
max       7879.420000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     104.000000
mean       97.070769
std       255.012160
min         0.000000
25%         1.000000
50%         3.775000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.00000,25514.725686,-0.194310,0.036967,0.744162,0.174545,-0.217414,0.107151,-0.093182,0.031783,0.222434,...,0.046047,-0.031386,-0.111706,-0.039470,0.007851,0.135895,0.022779,0.005987,0.003920,87.420700
0.00262,39929.000000,1.097669,-1.315782,0.659681,-0.683915,-1.342612,0.332629,-1.110900,0.194811,-0.248825,...,0.047664,-0.029662,-0.112320,-0.040265,0.007226,0.136322,0.023181,0.008097,0.004171,87.445979
1.00000,20683.201923,-7.697309,5.766703,-10.853666,5.865850,-5.424996,-2.275717,-7.641867,3.827809,-2.924282,...,0.663205,0.626795,-0.345972,-0.342944,-0.230514,0.299242,0.176522,0.811431,0.099914,97.070769

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent transactions

Number of Fraudulent Transactions --> 25

In [ ]:
legit_sample = legit.sample(n=25)

Concatenating two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample,fraud] , axis = 0 )

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
20255,30902,0.819883,-0.451978,0.089606,1.408561,-0.350679,-0.078990,0.251187,-0.003220,0.119279,...,0.009437,-0.265782,-0.306521,0.013062,0.661738,-0.357743,-0.020500,0.037888,199.00,0.0
17368,28658,1.145354,0.118386,0.378091,1.408596,-0.228577,-0.195729,0.026425,0.028131,0.411741,...,-0.105173,-0.127526,-0.060875,0.073306,0.632380,-0.311149,0.032769,0.016008,18.14,0.0
2839,2417,-0.339403,1.159029,1.300822,0.058592,0.053263,-0.972624,0.740550,-0.093539,-0.448055,...,-0.259686,-0.660597,-0.018147,0.343663,-0.148886,0.070672,0.247820,0.099010,3.87,0.0
13988,24856,-3.019163,-0.867828,0.185889,1.180677,3.176214,3.274869,-2.163350,1.982751,0.701305,...,-0.118212,-0.595009,-0.783634,1.004245,-0.335976,-0.327891,0.126779,-0.580409,0.00,0.0
14616,25827,1.188416,-0.177623,0.547988,-0.023005,-0.834331,-1.005948,-0.139958,-0.180738,0.382865,...,-0.103705,-0.395407,0.053507,0.451900,0.100981,0.898964,-0.079740,0.018107,51.32,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
30473,35942,-4.194074,4.382897,-5.118363,4.455230,-4.812621,-1.224645,-7.281328,3.332250,-3.679659,...,1.550473,0.614573,0.028521,0.013704,-0.149512,-0.131687,0.473934,0.473757,14.46,1.0
30496,35953,-4.844372,5.649439,-6.730396,5.252842,-4.409566,-1.740767,-6.311699,3.449167,-5.416284,...,1.194888,-0.845753,0.190674,-0.216443,-0.325033,-0.270328,0.210214,0.391855,111.70,1.0
31002,36170,-5.685013,5.776516,-7.064977,5.902715,-4.715564,-1.755633,-6.958679,3.877795,-5.541529,...,1.128641,-0.962960,-0.110045,-0.177733,-0.089175,-0.049447,0.303445,0.219380,111.70,1.0
33276,37167,-7.923891,-5.198360,-3.000024,4.420666,2.272194,-3.394483,-5.283435,0.131619,0.658176,...,-0.734308,-0.599926,-4.908301,0.410170,-1.167660,0.520508,1.937421,-1.552593,12.31,1.0
39183,39729,-0.964567,-1.643541,-0.187727,1.158253,-2.458336,0.852222,2.785163,-0.303609,0.940006,...,0.447180,0.536204,1.634061,0.203839,0.218749,-0.221886,-0.308555,-0.164500,776.83,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
1.0    104
0.0     25
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,27392.840000,-0.173972,0.040711,0.905924,0.290303,-0.095426,0.058052,-0.049639,0.156159,-0.014897,...,-0.145533,-0.062661,-0.065588,-0.017837,-0.032545,0.055826,0.027868,0.001089,-0.070629,55.205600
1.0,20683.201923,-7.697309,5.766703,-10.853666,5.865850,-5.424996,-2.275717,-7.641867,3.827809,-2.924282,...,0.663205,0.626795,-0.345972,-0.342944,-0.230514,0.299242,0.176522,0.811431,0.099914,97.070769

Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class',axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
20255  30902  0.819883 -0.451978  0.089606  1.408561 -0.350679 -0.078990
17368  28658  1.145354  0.118386  0.378091  1.408596 -0.228577 -0.195729
2839    2417 -0.339403  1.159029  1.300822  0.058592  0.053263 -0.972624
13988  24856 -3.019163 -0.867828  0.185889  1.180677  3.176214  3.274869
14616  25827  1.188416 -0.177623  0.547988 -0.023005 -0.834331 -1.005948
...      ...       ...       ...       ...       ...       ...       ...
30473  35942 -4.194074  4.382897 -5.118363  4.455230 -4.812621 -1.224645
30496  35953 -4.844372  5.649439 -6.730396  5.252842 -4.409566 -1.740767
31002  36170 -5.685013  5.776516 -7.064977  5.902715 -4.715564 -1.755633
33276  37167 -7.923891 -5.198360 -3.000024  4.420666  2.272194 -3.394483
39183  39729 -0.964567 -1.643541 -0.187727  1.158253 -2.458336  0.852222

             V7        V8        V9  ...       V20       V21       V22  \
20255  0.251187 -0.003220  0.119279  ...  0.216056  0.009437 -0.265782
17368  0.026425  0.028131  0.411741  ... -0.222018 -0.105173 -0.127526
2839   0.740550 -0.093539 -0.448055  ...  0.136317 -0.259686 -0.660597
13988 -2.163350  1.982751  0.701305  ... -0.471950 -0.118212 -0.595009
14616 -0.139958 -0.180738  0.382865  ...  0.037488 -0.103705 -0.395407
...         ...       ...       ...  ...       ...       ...       ...
30473 -7.281328  3.332250 -3.679659  ...  0.579098  1.550473  0.614573
30496 -6.311699  3.449167 -5.416284  ...  0.284555  1.194888 -0.845753
31002 -6.958679  3.877795 -5.541529  ...  0.299489  1.128641 -0.962960
33276 -5.283435  0.131619  0.658176  ... -2.169811 -0.734308 -0.599926
39183  2.785163 -0.303609  0.940006  ...  1.784449  0.447180  0.536204

            V23       V24       V25       V26       V27       V28  Amount
20255 -0.306521  0.013062  0.661738 -0.357743 -0.020500  0.037888  199.00
17368 -0.060875  0.073306  0.632380 -0.311149  0.032769  0.016008   18.14
2839  -0.018147  0.343663 -0.148886  0.070672  0.247820  0.099010    3.87
13988 -0.783634  1.004245 -0.335976 -0.327891  0.126779 -0.580409    0.00
14616  0.053507  0.451900  0.100981  0.898964 -0.079740  0.018107   51.32
...         ...       ...       ...       ...       ...       ...     ...
30473  0.028521  0.013704 -0.149512 -0.131687  0.473934  0.473757   14.46
30496  0.190674 -0.216443 -0.325033 -0.270328  0.210214  0.391855  111.70
31002 -0.110045 -0.177733 -0.089175 -0.049447  0.303445  0.219380  111.70
33276 -4.908301  0.410170 -1.167660  0.520508  1.937421 -1.552593   12.31
39183  1.634061  0.203839  0.218749 -0.221886 -0.308555 -0.164500  776.83

[129 rows x 30 columns]

In [ ]:
print(Y)

20255    0.0
17368    0.0
2839     0.0
13988    0.0
14616    0.0
        ...
30473    1.0
30496    1.0
31002    1.0
33276    1.0
39183    1.0
Name: Class, Length: 129, dtype: float64

Split thye data into Training data & Testing Data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(129, 30) (103, 30) (26, 30)

Model Training

Logistic Regression

In [49]:
model = LogisticRegression(max_iter=5000)

In [50]:
# training the logistic regression Model with Training Data
model.fit(X_train, Y_train)


#model.score(X_train, Y_train)

LogisticRegression(max_iter=5000)

In [47]:
#y_pred=model.predict(X_test)

In [48]:
#accuracy_score(y_pred,Y_test)

1.0

In [53]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [54]:
print('Accuracy on Traning data : ', training_data_accuracy)

Accuracy on Traning data :  1.0

In [55]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [56]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  1.0